### ISSUE TITLE
Named entities

### ISSUE THREAD

**Issue by ayebear** [ayebear/picoes#20]
Entities should be uniquely identifiable by a string name. An example use case of this is for a player entity:

```javascript
let player = world.entity("PlayerPrototype")
```

Now, we have to manage the "player" entity as a regular object, potentially putting it into a global state variable just to keep track of this. It would be much easier to be able to do this:

```javascript
// Entities with "name" properties
world.entity("PlayerPrototype").name = "player"

// Or, shorthand syntax to set the name
world.entity("PlayerPrototype", "player")
```
Other use cases could be to store renderers and other global states as named entities. While you could use components as "tags", this greatly slows down the indexing since it has to deal with many different component types, and could potentially collide with component names without adding some prefix like "name_".

To retrieve the entities later, you'd simply do this:
```javascript
world.get("player")
```

This get() method could also work with IDs or string IDs:
```javascript
let entity = world.entity()
world.get(entity.id)
world.get(entity.toString())
```

**Comment by Reificator** [comment]
In a table-based ECS the name would just be another component to be queried, often times in the same component as a GUID or other properties related to serialization.

I'm not sure how I would do this in a dictionary-based ECS though, beyond keeping two dictionaries.  But then you'll want to be able to lookup the name of a component you have a reference to if you go to make an editor frontend.

> While you could use components as "tags", this greatly slows down the indexing since it has to deal with many different component types

On a side note, treating empty components as tags and storing them differently than other component types could be of use here.  From the client's perspective it's fairly common to treat components as tags in similar libraries, users would expect to do the same here.

**Comment by ayebear** [comment]
Right, you could just use components to accomplish something similar, but component tags would not guarantee uniqueness, you'd end up with an array of entities if more than one entity had the same tag. I would probably use another dictionary to keep track of names - and the names are on the entity level, not the component level.

The empty component optimization might be good for other purposes too, but it might be negligible due to how components are currently indexed, unless there is a better way to do it.

**Comment by Reificator** [comment]
Yeah, the last paragraph was a side note on tags alone, multiple entities per tag is exactly what I'd expect to get back.
